export enum ErrorCodes {
  USER_HAS_NOT_PERMISSION = 100,
  USER_NOT_FOUND = 101,
  USER_HAS_NOT_OWNER_PERMISSION = 102,
  INCORRECT_OTP = 103,
  EMAIL_ALREADY_REGISTERED = 603,
  PHONE_ALREADY_REGISTERED = 604,

  CATEGORY_NOT_FOUND = 601,

  PRODUCT_NOT_FOUND = 301,
}
